import { Component } from '@angular/core';

// Function for member decorator
function hack(target, name, descriptor) {
  const original = descriptor.value;

  descriptor.value = (...args: [number]) => original.apply(this, args) + ' hi there...';

  return descriptor;
}

// Function for class decorator
function log(className) {
  console.log(className);
  return (...args) => {
    console.log('Arguments passed to this class\'s constructor are', args);
    return new className(args);
  }
}

@log // class's decorator
class MyClass {
  constructor(arg1, arg2) {
    console.log('Constructor fired!');
  }
}

const mc = new MyClass(5, 10);

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'intro2angular';

  constructor() {
    console.log('This statement was generated by the constructor', this.simpleMethod(5));
  }

  @hack // member's decorator
  simpleMethod(a: number) {
    return a * a;
  }
}
