import { Component } from '@angular/core';

function log(target, name, descriptor) {
  const original = descriptor.value;

  descriptor.value = (...args: [number]) => original.apply(this, args) + ' hi there...';

  return descriptor;
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'intro2angular';

  constructor() {
    console.log('This statement was generated by the constructor', this.simpleMethod(5));
  }

  @log
  simpleMethod(a: number) {
    return a * a;
  }
}
